name: MGDeathRun
main: com.comze_instancelabs.deathrun.Main
version: ${minigames.releaseversion}-${minigames.timestamp}
author: [InstanceLabs, TheMrQuake, mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   dr:
      description: Main command
      usage: /dr [action]
      aliases: [deathrun, mgdeathrun, dr]
